version: 2
jobs:
  build:
    working_directory: ~/ares
    docker:
      - image: circleci/clojure:lein-2.8.1
    steps:
      - checkout
      - restore_cache:
          key: ares-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: ares-{{ checksum "project.clj" }}
      - run: lein uberjar
      - persist_to_workspace:
          root: target
          paths:
            - uberjar
      - store_artifacts:
          path: target/uberjar/ares-standalone.jar
          destination: uberjar
  deploy:
    working_directory: ~/ares
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: target
      - run: docker build -t greg2010/ares .
      - run: docker tag greg2010/ares greg2010/ares:${CIRCLE_BRANCH}_${CIRCLE_SHA1:0:7}
      - run: docker tag greg2010/ares greg2010/ares:${CIRCLE_BRANCH}_latest
      - run: docker tag greg2010/ares greg2010/ares:latest
      - run: docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}
      - run: docker push greg2010/ares

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
